#!/bin/bash
cd $(dirname $0)
chmod u+x httpfs.jar
JAVA="java -jar httpfs.jar"
STRING="$@"
printf "\n\nRunning Server...COMMAND: httpfs ${STRING} \nResult:....\n\n" 2>&1 | tee -a "ServerTestResults.txt"
eval $JAVA $@ 2>&1 | tee -a "ServerTestResults.txt"
